### ISSUE TITLE
Pseudo tags inside Editor module

### ISSUE THREAD

**Issue by redaxmedia** [redaxmedia/redaxscript#271]
- [ ] 1. Pseudo tags have to be styled inside the preview mode 
- [ ] 2. Remove the "html to entities" encode and decode inside <code>editor.js</code>
- [ ] 3. Read-only mode for the pseudo tags inside the preview mode
- [ ] 4. Style <code>img</code> and <code>a</code> tag with empty src / href?

<pre>
img[src="http://"], a[src="http://"]
{
/* lets use the red like on remove formatting*/
}
</pre>

Here comes an approach: http://i.snag.gy/H0AxC.jpg

<pre>
.editor_preview function
{
	background: linear-gradient(#3db1f1, #0090db);
	color: #000;
	display: block;
	overflow: hidden;
	padding: 1em;
	position: relative;
	white-space: pre-wrap;
}

.editor_preview function:before
{
	font: 5em/5em "icon editor";
	margin-top: -2.5em;
	position: absolute;
	right: 5%;
	top: 50%;
}

.editor_preview function:after
{
/* code to overlay everything for read-only */
}

.editor_preview function:before
{
	content: '8';
}
</pre>

Another approach would be to use <code>text-indent: -999em</code> for the pseudo tag's content create cube with a icon that is 2 x 2em...

**Comment by joergsteinhauer** [comment]
- [x] 1. Pseudo tags have to be styled inside the preview mode 


### Version 1:
![rxs-1](https://cloud.githubusercontent.com/assets/1843754/6754455/e90c6fb4-cf1c-11e4-9512-3f83e62394bb.png)
```css
.editor_preview function:before {
    content: "8";
}
.editor_preview function:before {
    color: #0090db;
    font: 3em/1em "icon editor";
    position: absolute;
    right: 0.25em;
    top: 0.25em;
}
.editor_preview function {
    background: none repeat scroll 0 0 rgba(34, 34, 34, 0.05);
    border: 0.2em solid #b9b9b9;
    border-left: none;
    box-shadow: -0.75em 0 #0090db;
    display: block;
    font: 1.125em/1.5em monospace;
    margin: 3em;
    padding: 0.5em 4em 0.5em 1em;
    position: relative;
    white-space: pre-wrap;
}
```

### Version 2:
![rxs-2](https://cloud.githubusercontent.com/assets/1843754/6754453/e6b844cc-cf1c-11e4-9c0a-50a38cc09933.png)


```css
.editor_preview function:before {
    content: "8";
}
.editor_preview function:before {
    color: #0090db;
    font: 2.5em/1em "icon editor";
    margin-top: -0.5em;
    position: absolute;
    right: 0.25em;
    text-indent: 0;
    top: 50%;
}
.editor_preview function:after {
    content: "function";
    display: block;
    text-indent: 0;
}
.editor_preview function {
    background: rgba(34, 34, 34, 0.05);
    border: 0.2em solid #b9b9b9;
    border-left: none;
    box-shadow: -0.75em 0 #0090db;
    color: #0090db;
    display: block;
    font: bold 1.375em/1em monospace;
    height: 3em;
    margin: 3em;
    padding: 0.5em 4em 0.5em 1em;
    position: relative;
    text-indent: -999em;
    white-space: pre-wrap;
}
```
